server:
  port: 8501
spring:
  application:
    name: saber-auth
  datasource:
    url: jdbc:mysql://localhost:3306/saber_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    druid:
      filter: wall
mybatis:
  mapper-locations: classpath:mapper/*.xml

